import { Patient } from '../shared/models/patient.model';
import { Gender } from '../shared/enums/status.enums';

const today = new Date();

export const PATIENTS_MOCK: Patient[] = [
  {
    id: 'pat-001',
    mrn: 'PAT-001',
    firstName: 'John',
    lastName: 'Doe',
    fullName: 'John Doe',
    dateOfBirth: new Date(1985, 4, 15),
    gender: Gender.Male,
    nationality: 'US',
    nationalId: '123456789',
    phone: '+1 555-0101',
    email: 'john.doe@example.com',
    address: '123 Main St, NY',
    bloodType: 'O+',
    emergencyContactName: 'Jane Doe',
    emergencyContactPhone: '+1 555-0102',
    allergies: ['Penicillin'],
    chronicDiseases: ['Hypertension'],
    fixedMedications: ['Lisinopril'],
    status: 'Active',
    createdAt: new Date(today.getTime() - 30 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    createdBy: 'sys',
    updatedBy: 'sys'
  },
  {
    id: 'pat-002',
    mrn: 'PAT-002',
    firstName: 'Alice',
    lastName: 'Smith',
    fullName: 'Alice Smith',
    dateOfBirth: new Date(1990, 8, 22),
    gender: Gender.Female,
    nationality: 'UK',
    nationalId: '987654321',
    phone: '+44 7700 900077',
    email: 'alice.smith@example.com',
    address: '456 London Rd, London',
    bloodType: 'A-',
    emergencyContactName: 'Bob Smith',
    emergencyContactPhone: '+44 7700 900088',
    allergies: [],
    chronicDiseases: [],
    fixedMedications: [],
    status: 'Active',
    createdAt: new Date(today.getTime() - 15 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    createdBy: 'sys',
    updatedBy: 'sys'
  },
  {
    id: 'pat-003',
    mrn: 'PAT-003',
    firstName: 'Michael',
    lastName: 'Johnson',
    fullName: 'Michael Johnson',
    dateOfBirth: new Date(1975, 2, 10),
    gender: Gender.Male,
    nationality: 'CA',
    nationalId: '567890123',
    phone: '+1 416-555-0198',
    email: 'mjohnson@example.com',
    address: '789 Maple Ave, Toronto',
    bloodType: 'B+',
    emergencyContactName: 'Sarah Johnson',
    emergencyContactPhone: '+1 416-555-0199',
    allergies: ['Peanuts', 'Latex'],
    chronicDiseases: ['Type 2 Diabetes'],
    fixedMedications: ['Metformin'],
    status: 'Active',
    createdAt: new Date(today.getTime() - 60 * 24 * 60 * 60 * 1000),
    updatedAt: new Date(),
    createdBy: 'sys',
    updatedBy: 'sys'
  }
];
